# SPDX-License-Identifier: MIT-0
---
- name: 2700K
  ansible.builtin.shell:
    cmd: "DISPLAY={{ controls_xdisplay }} redshift -P -O 2700"
  ignore_errors: false
  when:
    - controls_redshift
  tags:
    - 2700K
