# SPDX-License-Identifier: MIT-0
---
- name: 3500K
  ansible.builtin.shell:
    cmd: "DISPLAY={{ controls_xdisplay }} redshift -P -O 3500"
  ignore_errors: false
  when:
    - controls_redshift
  tags:
    - 3500K
