# SPDX-License-Identifier: MIT-0
---
- name: 4800K
  ansible.builtin.shell:
    cmd: "DISPLAY={{ controls_xdisplay }} redshift -P -O 4800"
  ignore_errors: false
  when:
    - controls_redshift
  tags:
    - 4800K
