# SPDX-License-Identifier: MIT-0
---
- name: Balanced
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo balanced | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  ignore_errors: false
  become: true
  when:
    - controls_power
  tags:
    - balanced

# TODO: an alternative way that I once tried with KDE was this:
# cmd: "qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/PowerProfile org.kde.Solid.PowerManagement.Actions.PowerProfile.setProfile balanced"
