# SPDX-License-Identifier: MIT-0
---
- name: Performance
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  ignore_errors: false
  become: true
  when:
    - controls_power
  tags:
    - performance

# cmd: "qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/PowerProfile org.kde.Solid.PowerManagement.Actions.PowerProfile.setProfile performance"
