# SPDX-License-Identifier: MIT-0
---
- name: Enable wake-on-lan (must be root)
  ansible.builtin.import_tasks:
    file: wakeonlan.yml
  when:
    - controls_suspend
    - controls_wol_nic != ""
  tags:
    - suspend

- name: Suspend
  ansible.builtin.shell:  # noqa command-instead-of-module
    cmd: "systemctl suspend"
  ignore_errors: false
  become: true
  when:
    - controls_suspend
  tags:
    - suspend
